/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convertidortemp;

import javax.swing.JOptionPane;

/**
 *
 * @author Celia
 */
public class ConvertidorCelsFah extends javax.swing.JFrame {

    /**
     * Creates new form ConvertidorCelsFah
     */
    public ConvertidorCelsFah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlTitulo2 = new javax.swing.JLabel();
        jlIngrese = new javax.swing.JLabel();
        jtDatosUsuario = new javax.swing.JTextField();
        jbConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTitulo.setBackground(new java.awt.Color(0, 102, 102));
        jlTitulo.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(0, 153, 153));
        jlTitulo.setText("Convertidor de Temperatura");

        jlTitulo2.setBackground(new java.awt.Color(0, 153, 153));
        jlTitulo2.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jlTitulo2.setForeground(new java.awt.Color(0, 153, 153));
        jlTitulo2.setText("Celsius - Fahrenheit");

        jlIngrese.setBackground(new java.awt.Color(153, 0, 255));
        jlIngrese.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jlIngrese.setForeground(new java.awt.Color(102, 0, 204));
        jlIngrese.setText("Ingrese Temperatura en Celsius:");

        jbConvertir.setBackground(new java.awt.Color(0, 153, 153));
        jbConvertir.setForeground(new java.awt.Color(102, 0, 204));
        jbConvertir.setText("Convertir");
        jbConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jlTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlTitulo2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlIngrese)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(138, 138, 138)
                                    .addComponent(jbConvertir))))
                        .addGap(30, 30, 30)
                        .addComponent(jtDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTitulo2)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIngrese)
                    .addComponent(jtDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jbConvertir)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConvertirActionPerformed
       try{
        String nroCadena=jtDatosUsuario.getText(); 
int nro=Integer.parseInt(nroCadena);
double resul=(nro * 9/5)+ 32;
JOptionPane.showMessageDialog(this,resul + " º Fahrenheit");
       } catch (NumberFormatException nf){
    JOptionPane.showMessageDialog(this,"Por favor digite solo numeros");
    jtDatosUsuario.requestFocus();
    }//GEN-LAST:event_jbConvertirActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertidorCelsFah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertidorCelsFah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertidorCelsFah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertidorCelsFah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertidorCelsFah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbConvertir;
    private javax.swing.JLabel jlIngrese;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlTitulo2;
    private javax.swing.JTextField jtDatosUsuario;
    // End of variables declaration//GEN-END:variables
}
